### ISSUE TITLE
As a user I would like to be able to start a chat with an instructor.

### ISSUE THREAD

**Issue by kzikaras** [kzikaras/bloc-capstone#4]
Setup chat functionality for users.
![Imgur](https://i.imgur.com/KZT95HT.jpg)

**Comment by johnksawers** [comment]
Focus on the user's experience in this one too - they don't care about ActionCable

"As a user, I want to chat with my Instructor so that I can upgrade my iphone"

Part of this is to keep the user's ultimate goal in mind, and not focus on the specific implementation, but also these user stories will often be written by product or project managers, and you dobn't want them specifying your technology choices in the story. 

Also, by not specifying the impmenentation details, you won't have to change the ticket if you decide not to use ActionCable because something else is better.
